[package]
name = "morg-parser"
edition.workspace = true
version.workspace = true
authors.workspace = true
description.workspace = true
documentation.workspace = true
license.workspace = true
readme = "README.md"
categories.workspace = true
keywords.workspace = true
repository.workspace = true
exclude.workspace = true

[lib]
path = "src/lib.rs"

[dependencies]
chrono.workspace = true
serde.workspace = true
serde_yaml.workspace = true
